name: Repro_R_SCONE
channels:
 - conda-forge
dependencies:
  - r-base=4.2.3
  - r-readxl
  - r-tidyverse
  - r-lubridate
  - r-mgcv
  - r-mgcv.helper
  - r-emmeans
  - r-ggsignif
  - r-viridis
  - r-cowplot
