name: Repro_R
dependencies:
  - r-base=4.1
  - r-shiny
  - r-devtools
  - r-caret
  - r-ggplot2
  - r-gtrendsR
  - r-cowplot
  - r-gridExtra
  - r-corrplot
  - r-ISOweek
  - r-glmnet
  - r-doParallel
